---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - "${JELLYFIN_CONFIG_HOME}:/config"
      - tv:/data/tvshows
      - movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: host
    depends_on:
      - jellyfin
volumes:
  movies:
    driver: local
    driver_opts:
      type: none
      device: ${MOVIE_HOME}
      o: bind
  tv:
    driver: local
    driver_opts:
      type: none
      device: ${TVSHOW_HOME}
      o: bind
