---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - "${JELLYFIN_CONFIG_HOME}:/config"
      - tv:/data/tvshows
      - movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: host
    depends_on:
      - jellyfin
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${PROWLARR_CONFIG_HOME}:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - pirate
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${SONARR_CONFIG_HOME}:/config
      - tv:/tv
      - downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - pirate
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${RADARR_CONFIG_HOME}:/config
      - movies:/movies
      - downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - pirate
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${TRANSMISSION_CONFIG_HOME}:/config
      - downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - pirate
volumes:
  movies:
    driver: local
    driver_opts:
      type: none
      device: ${MOVIE_HOME}
      o: bind
  tv:
    driver: local
    driver_opts:
      type: none
      device: ${TVSHOW_HOME}
      o: bind
  downloads:
    driver: local
    driver_opts:
      type: none
      device: ${DOWNLOAD_HOME}
      o: bind
networks:
  pirate:
    driver: bridge
