---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${JELLYFIN_CONFIG_HOME}:/config"
      - "${JELLYFIN_TVSHOW_HOME}:/data/tvshows"
      - "${JELLYFIN_MOVIE_HOME}:/data/movies"
    ports:
      - 8096:8096
    restart: unless-stopped
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: host
